application: four-pics-one-word-solver
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /_ah/spi/.*
  script: api.app
- url: .*
  script: game.app

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

builtins:
- appstats: on
